### ISSUE TITLE
Unable to resolve module @openmobilehub/maps-plugin-mapbox 

### ISSUE THREAD

**Issue by TrejoCode** [openmobilehub/react-native-omh-maps#100]
Hello, I'm trying to run the app, I'm using: core and openstreetmaps.

```
    "@openmobilehub/maps-core": "^1.0.0",
    "@openmobilehub/maps-plugin-openstreetmap": "^1.0.0",
```

Then I run: npm run android:

```
error Unable to resolve module @openmobilehub/maps-plugin-mapbox from /Users/sergiotrejo/Documents/traxion/biz_passenger/node_modules/@openmobilehub/maps-core/src/utils/optionalPlugins/_optionalMapboxPlugin.ts: @openmobilehub/maps-plugin-mapbox could not be found within the project or in these directories:
  node_modules/@openmobilehub/maps-core/node_modules
  node_modules
  ../../../node_modules
> 1 | export default require('@openmobilehub/maps-plugin-mapbox');
    |                         ^
  2 |.
```

**Comment by maciekBudzinski** [comment]
Hi @TrejoCode! Thanks for reporting the issue. Can you please specify the react-native version that you use, so we can reproduce it and work on the fix.

**Comment by TrejoCode** [comment]
> Hi @TrejoCode! Thanks for reporting the issue. Can you please specify the react-native version that you use, so we can reproduce it and work on the fix.

I'm sorry I forgot it.

React Native 0.73.6

**Comment by maciekBudzinski** [comment]
@TrejoCode Thanks, I want let you know that later this week we have planning session and we are going to take care about this issue. I will get back to you once we have some updates.

**Comment by dzuluaga** [comment]
@Nataliagros Friendly ping.

**Comment by adamTrz** [comment]
Hi @TrejoCode - thanks for replying and apologies for delayed answer
Does this issue still exists?
