### ISSUE TITLE
Modules are referencing `@openmobilehub/maps-core@1.0.0-beta`, but this version doesn't exist [BLOCKING ISSUE WHILE USING OTHER MODULES]

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-maps#101]
I encountered an issue while installing the `@openmobilehub/maps-plugin-googlemaps` and `@openmobilehub/maps-plugin-openstreetmap` packages. These modules have a peer dependency on `@openmobilehub/maps-core@1.0.0-beta`, but it seems that this version doesn't exist in the npm registry.

**Steps to Reproduce:**

1. Run the following command in a project:
   ```bash
   npm install @openmobilehub/auth-google @openmobilehub/maps-plugin-googlemaps @openmobilehub/maps-plugin-openstreetmap
   ```
2. The following warnings and errors are displayed:
   ```
   npm WARN Could not resolve dependency:
   npm WARN peer @openmobilehub/maps-core@"1.0.0-beta" from @openmobilehub/maps-plugin-googlemaps@1.0.0
   npm WARN node_modules/@openmobilehub/maps-plugin-googlemaps
   npm WARN   @openmobilehub/maps-plugin-googlemaps@"^1.0.0" from the root project

   npm ERR! code ETARGET
   npm ERR! notarget No matching version found for @openmobilehub/maps-core@1.0.0-beta.
   ```

**Expected Behavior:**

The installation should succeed without errors or warnings. The correct version of `@openmobilehub/maps-core` should be referenced by the plugins.

**Actual Behavior:**

The installation fails because `@openmobilehub/maps-core@1.0.0-beta` does not exist in the npm registry.

**Additional Information:**

- It appears that both `@openmobilehub/maps-plugin-googlemaps` and `@openmobilehub/maps-plugin-openstreetmap` are incorrectly referencing `@openmobilehub/maps-core@1.0.0-beta`.

Incorrect references:
- [Google Maps](https://github.com/openmobilehub/react-native-omh-maps/blob/main/packages/plugin-azuremaps/package.json#L55)
- [Mapbox](https://github.com/openmobilehub/react-native-omh-maps/blob/main/packages/plugin-googlemaps/package.json#L55)
- [Azure Maps](https://github.com/openmobilehub/react-native-omh-maps/blob/main/packages/plugin-azuremaps/package.json#L55)
- [OpenStreetMap](https://github.com/openmobilehub/react-native-omh-maps/blob/main/packages/plugin-openstreetmap/package.json#L55)

- The latest available version in the npm registry for `@openmobilehub/maps-core` is `1.0.0`.

**Suggested Solution:**

- Update the peer dependency of these modules to reference the correct existing version of `@openmobilehub/maps-core`, such as `1.0.0`.

**More context**
- This issue also occurs after trying to add an unrelated module such as `npm add @openmobilehub/auth-google`

Thank you for looking into this issue!

**Comment by maciekBudzinski** [comment]
Thank you for highlighting the issue.
It seems to be fixed with the 1.0.2 release.

If you still struggle with some issues, make sure to follow the [core](https://openmobilehub.github.io/react-native-omh-maps/docs/core) instruction first: https://openmobilehub.github.io/react-native-omh-maps/docs/core and the plugins: [google](https://openmobilehub.github.io/react-native-omh-maps/docs/googlemaps) and [openstreetmap](https://openmobilehub.github.io/react-native-omh-maps/docs/openstreetmap).

I've also prepared the minimal sample that you can found [here](https://github.com/maciekBudzinski/omh-maps-minimal-sample).

**Comment by adamTrz** [comment]
Hi @dzuluaga - closing the issue since it seems to have been resolved with lates release. 
In case of any issues still reappearing please reopen! 👍

**Comment by dzuluaga** [comment]
Yes, the issue was resolved after the modules were published. Moving forward, it would be great if we could avoid similar issues by having the team cross-test each other's work. This will help us catch any potential problems earlier.
