### ISSUE TITLE
Navigation through the documentation could be better

### ISSUE THREAD

**Issue by draggie** [openmobilehub/react-native-omh-maps#107]
There’s a lack of clear information about the capabilities of the components—the navigation between the core documentation and the providers is not very intuitive. For example, to find out how to change something like the marker icon, you have to search a bit. There’s that compatibility table, but I get the impression that it’s not very clear.
It would be better to add few more examples of usage of component or separate pages which will explain in detail the possibilities and limitations of each component for example how this is done in one of providers - Mapbox https://github.com/rnmapbox/maps/blob/main/docs/UserLocation.md

**Comment by adamTrz** [comment]
Hey @draggie 
Thanks for the feedback :) 
It's a very good idea and I think it's a very good candidate to add to next phase - OMH 2.5

Closing for now :)
