### ISSUE TITLE
Map View is not loading sometimes on android

### ISSUE THREAD

**Issue by draggie** [openmobilehub/react-native-omh-maps#109]
On Android, when I add my own markers, the map often doesn’t load—I’m not sure what’s going on. Occasionally, this message appears: `Attempt to invoke virtual method 'org.osmdroid.views.MapViewRepository org.osmdroid.views.MapView.getRepository()` on a null object reference.’ 
In my case, the app is different in that it renders these markers dynamically from a collection after it’s loaded—what’s strange is that it works sometimes, in most cases there is no error even - just empty screen.

```
export const WeatherMap = () => {
  const cities = useCities();
  const forecast = useLoadForecast(cities.data);
  const markers = useMemo(
    () =>
      forecast.data?.list.map(item => (
        <OmhMarker
          key={item.id}
          icon={{
            uri: `https://openweathermap.org/img/w/${item.weather[0].icon}.png`,
            width: 150,
            height: 150,
          }}
          title={`${item.name}: ${item.main.temp}C`}
          position={{
            latitude: item.coord.lat,
            longitude: item.coord.lon,
          }}
        />
      )),
    [forecast],
  );

  return (
    <View style={style.container}>
      <OmhMapView>{markers}</OmhMapView>
    </View>
  );
};

```

**Comment by adamTrz** [comment]
That's strange, but I would guess that markers are being created **before** Map View is created? 🤔 
I've found similar issue here: https://github.com/osmdroid/osmdroid/issues/1570

Could you maybe try to attach some state to `onMapReady` callback and create markers then? 

Sth like that I guess? 

```ts
const [isMapReady, setIsMapReady] = useState(false)
//....
  const markers = useMemo(
    () => !isMapReady ? [] : 
      forecast.data?.list.map(item => (
        <OmhMarker {...props}        />
      )),
    [forecast],
  );

  return (
    <View style={style.container}>
      <OmhMapView 
         onMapReady={setIsMapReady(true)}>
         {markers}
     </OmhMapView>
    </View>
```

**Comment by adamTrz** [comment]
Closing but feel free to reopen if the issue still appears 👍
