### ISSUE TITLE
Add Animations for OMH Maps React Native Sample App in README.md and Getting Started Docs

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-maps#44]
Same case https://github.com/openmobilehub/react-native-omh-auth/issues/62. Thanks for your attention.

**Comment by dzuluaga** [comment]
@Nataliagros friendly ping. It's been open for a while and and these animations are crucial to understand the SDKs. Thanks.

**Comment by dzuluaga** [comment]
I'm confused. 48 GIFs sounds like a huge list of videos. Why would maps require that many videos? We just want to showcase the functionality with GMS and non-GMS devices and showcase in the same video the sample app functionality. Thanks.

**Comment by DamianNowak5f** [comment]
@dzuluaga we would have to create ~~48~~ 42 GIFs (I miscounted the functionalities and provided the wrong number to Natalia - apologies) if we wanted to maintain the same GIFs table that we have in the [**android-omh-maps**](https://github.com/openmobilehub/android-omh-maps?tab=readme-ov-file#a-single-codebase-running-seamlessly-on-any-device). 

There, we have a table made of four providers:
- Google Maps
- Open Street Maps
- MapBox
- Azure Maps

and seven functionalities:
- Camera Map
- Location Sharing Map
- Marker Map
- Info Windows Map
- Polyline Map
- Polygon Map
- Custom Styles Map 

So in total 24 GIFs.

For **react-native-omh-maps** we have additional two providers: 
- Apple Maps on iOS
- Google Maps on iOS

So If we wanted to create exact same table we would have to create GIFs for six providers and seven functionalities, resulting in 42 GIFs. 

Our proposition is to create GIFs only for the Camera Map functionality - the first one that is shown in the **android-omh-maps** [README](https://github.com/openmobilehub/android-omh-maps?tab=readme-ov-file#a-single-codebase-running-seamlessly-on-any-device).

**Comment by dzuluaga** [comment]
Gotcha. Thanks for the explanation. Sounds good. 6 videos. But how instead of Camera Map functionality all the functionality? I understand the page will take longer to load because of the file sizes.

**Comment by dzuluaga** [comment]
One idea that @Nataliagros and I discussed on our last call was to record a single video in a single short (it doesn't need to be perfect). Then split this video into smaller ones after recording it. Will that make the job easier?
