### ISSUE TITLE
Automate APK and IPA Generation

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-maps#65]
Create a GitHub Actions workflow to automate the generation of APKs for Android and IPAs for iOS, enabling easy access for testers and stakeholders.

**Requirements:**
1. **Automate Builds**: Generate APKs (release and debug) and IPAs.
2. **Easy Access**: Ensure APKs and IPAs can be downloaded from GitHub releases.
3. **Minimal Intervention**: Workflow should run with minimal manual steps.
4. **Manual Triggering**: Support manual workflow runs.
5. **Security**: Use GitHub secrets for sensitive data.
6. **Documentation**: Provide setup and usage instructions.

**Acceptance Criteria:**
- Automated APK and IPA generation.
- Easy download from GitHub releases.
- Supports manual triggering and uses GitHub secrets.

**Comment by andrei-zgirvaci** [comment]
Hey @dzuluaga, thanks for bringing this to our attention! This was addressed and should be fixed in https://github.com/openmobilehub/react-native-omh-maps/pull/99/commits/5ef180f4a4edb28363f102fed54f9cdc1db8d5ad.
