### ISSUE TITLE
App Fails to Start After Adding @openmobilehub/maps-plugin-mapbox

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-maps#88]
After installing `@openmobilehub/maps-plugin-mapbox` in a new app, the app fails to start.

**Steps to Reproduce:**

1. Run `yarn add @openmobilehub/maps-plugin-mapbox`
2. Run `yarn android`

**Error:**

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.mapbox.maps:android:11.1.0.
     Required by:
         project :app > com.openmobilehub.android.maps:plugin-mapbox:2.1.0
```

**Temporary Solution:**

Removing the dependency from `node_modules` allows the app to start, but this isn't a viable solution.

**Question:**

Am I missing something? How can I use Mapbox in my app like I use Google Maps?

Any help or guidance would be appreciated. Thanks!

**Comment by maciekBudzinski** [comment]
Hi @dzuluaga It looks like you miss the step with maven configuration: https://www.openmobilehub.com/react-native-omh-maps/docs/mapbox#maven.

Pleas try to add it and let us know if it works.

**Comment by dzuluaga** [comment]
Thanks, @maciekBudzinski. That did the trick! I wonder if the Maven section should go before the Credentials section. What do you think? I'll close the bug, but I look forward to hearing your thoughts.
