### ISSUE TITLE
Separate Task for Publishing Docs Missing for RN OMH Maps

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/react-native-omh-maps#91]
The RN OMH Maps repository do not have a separate task to publish documentation, similar to the one found [here](https://github.com/openmobilehub/android-omh-auth/issues/63). I created a quick workaround in the [react-native-omh-auth repository](https://github.com/openmobilehub/react-native-omh-auth/blob/main/.github/workflows/build-publish-docs.yml), but it required changes in the `turbo.json` file, specifically modifying `pipelines` to `tasks`.

#### Expected Behavior

A separate task should exist to handle the publishing of documentation for RN OMH Auth, similar to other repositories.

#### Steps to Reproduce

1. Check the current workflow configuration in the RN OMH Auth repositories.
2. Notice the lack of a separate task for publishing documentation.

#### Workaround

I made changes in the `react-native-omh-auth` repository by:
1. Creating a new workflow file: `.github/workflows/build-publish-docs.yml`
2. Modifying `turbo.json`:
   - Changed `pipelines` to `tasks` to address the issue.

#### Proposed Solution

- Create a separate task for publishing docs in RN OMH Maps and Auth repositories.
- Ensure the task is similar to the one referenced above to maintain consistency across repositories.

#### Additional Context

Natalia & Andrei - This issue reflects a recurring problem that should have been addressed based on our previous experience. Why are we repeating the same issues? A collective approach to streamline documentation publishing tasks across all repositories would prevent these repetitive fixes. Esp. when it's the same team working across the same modules.

Please address this issue to maintain a streamlined workflow for documentation publishing.

**Comment by andrei-zgirvaci** [comment]
Hey @dzuluaga, thanks for bringing this to our attention! This was addressed and should be fixed in https://github.com/openmobilehub/react-native-omh-maps/pull/98/commits/230ad50ed930a7c494774333791d75ba1ca4355b.
